### ISSUE TITLE
Rename library / project / repository to "Trakt.NET"

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#3]
Original Issue: https://github.com/henrikfroehling/TraktApiSharp/issues/58

- [x] #8 Change the global namespace "TraktApiSharp" to "TraktNET"
- [x] #9 Rename Visual Studio project
- [x] #14 Replace all occurrences of "TraktApiSharp" with "Trakt.NET" in all misc files (readme, license, contributing, coding_style)
- [x] #15 Update readme (Add some information message)
