### ISSUE TITLE
Version 1.0.0 ToDo

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#4]
Original Issue: https://github.com/henrikfroehling/TraktApiSharp/issues/16

#### ToDo
**Version 1.0.0 Alpha 1**
- [x] [old/#17](https://github.com/henrikfroehling/TraktApiSharp/issues/17) New and better request implementation
- [x] [old/#44](https://github.com/henrikfroehling/TraktApiSharp/issues/44) New and better response implementation
- [x] [old/#34](https://github.com/henrikfroehling/TraktApiSharp/issues/34) Convert PCL to .NET Standard

**Version 1.0.0 Alpha 2**
- [x] [old/#18](https://github.com/henrikfroehling/TraktApiSharp/issues/18) Reduce indirections in object properties
- [x] [old/#20](https://github.com/henrikfroehling/TraktApiSharp/issues/20) Optimize deserialization of json data
- [x] [old/#43](https://github.com/henrikfroehling/TraktApiSharp/issues/43) Remove Images option in TraktExtendedInfo
- [x] [old/#59](https://github.com/henrikfroehling/TraktApiSharp/issues/59) System.NullReferenceException When getting popular shows

**Version 1.0.0 Alpha 3**
- [x] [old/#21](https://github.com/henrikfroehling/TraktApiSharp/issues/21) Improve http client handling
- [x] [old/#69](https://github.com/henrikfroehling/TraktApiSharp/issues/69) Add support for "networks" GET request (for version 1.0.0)
- [x] [old/#70](https://github.com/henrikfroehling/TraktApiSharp/issues/70) Add support for "certifications/{type}" GET request (for version 1.0.0)
- [x] [old/#71](https://github.com/henrikfroehling/TraktApiSharp/issues/71) Add support for "users/hidden/{section}" POST request (for version 1.0.0)
- [x] [old/#72](https://github.com/henrikfroehling/TraktApiSharp/issues/72) Add support for "users/hidden/{section}/remove" POST request (for version 1.0.0)
- [x] [old/#75](https://github.com/henrikfroehling/TraktApiSharp/issues/75) Optimize serialization of json data
- [x] [old/#77](https://github.com/henrikfroehling/TraktApiSharp/issues/77) Fix serialization of objects in post builder
- [x] [old/#78](https://github.com/henrikfroehling/TraktApiSharp/issues/78) Implement json deserialization for authorization objects
- [x] [old/#79](https://github.com/henrikfroehling/TraktApiSharp/issues/79) Remove prefix Trakt from internal type names
- [x] [old/#83](https://github.com/henrikfroehling/TraktApiSharp/issues/83) Add missing "network" property in ITraktSeason
- [x] [old/#87](https://github.com/henrikfroehling/TraktApiSharp/issues/87) Move tests from old test project into new test project
- [x] [old/#88](https://github.com/henrikfroehling/TraktApiSharp/issues/88) Add missing "last_episode" property in ITraktShowProgress
- [x] [old/#89](https://github.com/henrikfroehling/TraktApiSharp/issues/89) Add "dolby_atmos" and "dts_x" in TraktMediaAudio
- [x] [old/#103](https://github.com/henrikfroehling/TraktApiSharp/issues/103) Fix module tests
- [x] [old/#106](https://github.com/henrikfroehling/TraktApiSharp/issues/106) Add support for X-Item-ID and X-Item-Type response headers
- [x] [old/#107](https://github.com/henrikfroehling/TraktApiSharp/issues/107) Add support for "comments/{id}/item" GET request
- [x] [old/#108](https://github.com/henrikfroehling/TraktApiSharp/issues/108) Add support for "comments/recent/{comment_type}/{type}" GET request
- [x] [old/#109](https://github.com/henrikfroehling/TraktApiSharp/issues/109) Add support for "comments/{id}/likes" GET request
- [x] [old/#110](https://github.com/henrikfroehling/TraktApiSharp/issues/110) Add missing "country" property in ITraktMovie
- [x] [old/#111](https://github.com/henrikfroehling/TraktApiSharp/issues/111) Add "comment_count" property in ITraktMovie, ITraktShow, ITraktSeason and ITraktEpisode
- [x] [old/#116](https://github.com/henrikfroehling/TraktApiSharp/issues/116) Add support for "people/{id}/lists/{type}/{sort}" GET request
- [x] [old/#117](https://github.com/henrikfroehling/TraktApiSharp/issues/117) Add support for "comments/trending/{comment_type}/{type}?{include_replies}" GET request
- [x] [old/#118](https://github.com/henrikfroehling/TraktApiSharp/issues/118) Add support for "comments/recent/{comment_type}/{type}?{include_replies}" GET request
- [x] [old/#119](https://github.com/henrikfroehling/TraktApiSharp/issues/119) Add support for "comments/updates/{comment_type}/{type}?{include_replies}" GET request
- [x] [old/#120](https://github.com/henrikfroehling/TraktApiSharp/issues/120) Add support for "lists/trending" GET request
- [x] [old/#121](https://github.com/henrikfroehling/TraktApiSharp/issues/121) Add support for "lists/popular" GET request
- [x] [old/#122](https://github.com/henrikfroehling/TraktApiSharp/issues/122) Add support for "include_replies" parameter in "users/id/comments" GET request
- [x] [old/#123](https://github.com/henrikfroehling/TraktApiSharp/issues/123) Make "sort_how" and "sort_by" optional in "users/{id}/lists" and "users/{id}/lists/{list_id}" requests
- [x] [old/#124](https://github.com/henrikfroehling/TraktApiSharp/issues/124) Allow multiple types as filter in "users/{id}/lists/{list_id}/items/{type}" request
- [x] [old/#129](https://github.com/henrikfroehling/TraktApiSharp/issues/129) Add "reset_at" property in ITraktShowWatchedProgress
- [x] [old/#130](https://github.com/henrikfroehling/TraktApiSharp/issues/130) Add flag for "progress_watched_reset" section in TraktHiddenItemsSection

**Version 1.0.0 Beta 1**
- [x] [old/#57](https://github.com/henrikfroehling/TraktApiSharp/issues/57) Move all examples into their own repository
- [x] #3  Rename library / project / repository to "Trakt.NET"
- [x] #23 Fix serialization service
- [x] #27 Add missing "token" property in ITraktAccountSettings
- [x] #30 post builder feature: add support for posting collected episodes without ids
- [x] #33 Implement missing json object and array reader
- [x] #34 Implement missing json object and array writer
- [x] #35 Fix post builder for sync collection post
- [x] #36 Refreshing authorization not working with expired or invalid access token
- [x] #37 Revoking authorization not working with expired or invalid access token
- [x] #49 Epic: Improve test coverage - Part 1
- [x] #61 Wrong type assignment for lists
- [x] #62 Bad Request when adding items to a list
- [x] #64 Exception when search text query is empty
- [x] #65 Invalid implementation for Networks / List / Get networks
- [x] #72 Add missing filter support for text query search
- [x] #94 Redundant checks for ITraktMovie properties in TraktScrobbleModule

**Version 1.0.0**
- [x] #28 Update source code documentation
- [x] #107 Split up test project in multiple test projects (release)
- [x] #117 Split up TraktNET.Objects.Tests in multiple test projects (release)
- [x] #121 Improve / replace UriTemplate implementation (release)
- [x] #125 Add support for new people methods
