### ISSUE TITLE
Checklist API Endpoints

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#457]
### Authentication - OAuth
TODO

---

### Authentication - Devices
TODO

---

#### My Shows
- [ ] [Get shows](https://trakt.docs.apiary.io/#reference/calendars/my-shows/get-shows)
#### My New Shows
- [ ] [Get new shows](https://trakt.docs.apiary.io/#reference/calendars/my-new-shows/get-new-shows)
#### My Season Premieres
- [ ] [Get season premieres](https://trakt.docs.apiary.io/#reference/calendars/my-season-premieres/get-season-premieres)
#### My Movies
- [ ] [Get movies](https://trakt.docs.apiary.io/#reference/calendars/my-movies/get-movies)
#### My DVD
- [ ] [Get DVD releases](https://trakt.docs.apiary.io/#reference/calendars/my-dvd/get-dvd-releases)
#### All Shows
- [ ] [Get shows](https://trakt.docs.apiary.io/#reference/calendars/all-shows/get-shows)
#### All New Shows
- [ ] [Get new shows](https://trakt.docs.apiary.io/#reference/calendars/all-new-shows/get-new-shows)
#### All Season Premieres
- [ ] [Get season premieres](https://trakt.docs.apiary.io/#reference/calendars/all-season-premieres/get-season-premieres)
#### All Movies
- [ ] [Get movies](https://trakt.docs.apiary.io/#reference/calendars/all-movies/get-movies)
#### All DVD
- [ ] [Get DVD releases](https://trakt.docs.apiary.io/#reference/calendars/all-dvd/get-dvd-releases)

---

### Checkin
- [ ] [Check into an item](https://trakt.docs.apiary.io/#reference/checkin/checkin/check-into-an-item)
- [ ] [Delete any active checkins](https://trakt.docs.apiary.io/#reference/checkin/checkin/delete-any-active-checkins)

---

#### List
- [ ] [Get certifications](https://trakt.docs.apiary.io/#reference/certifications/list/get-certifications)

---

### Comments
TODO

---

#### List
- [ ] [Get countries](https://trakt.docs.apiary.io/#reference/countries/list/get-countries)

---

#### List
- [ ] [Get genres](https://trakt.docs.apiary.io/#reference/genres/list/get-genres)

---

#### List
- [ ] [Get languages](https://trakt.docs.apiary.io/#reference/languages/list/get-languages)

---

### Lists
TODO

---

### Movies
TODO

---

### Networks
TODO

---

### People
TODO

---

### Recommendations
TODO

---

### Scrobble
TODO

---

### Search
TODO

---

### Shows
TODO

---

### Seasons
TODO

---

### Episodes
TODO

---

### Sync
TODO

---

### Users
TODO

**Comment by henrikfroehling** [comment]
### Calendars
#### My Shows
- [ ] [Get shows](https://trakt.docs.apiary.io/#reference/calendars/my-shows/get-shows) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L50
#### My New Shows
- [ ] [Get new shows](https://trakt.docs.apiary.io/#reference/calendars/my-new-shows/get-new-shows) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L91
#### My Season Premieres
- [ ] [Get season premieres](https://trakt.docs.apiary.io/#reference/calendars/my-season-premieres/get-season-premieres) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L132
#### My Movies
- [ ] [Get movies](https://trakt.docs.apiary.io/#reference/calendars/my-movies/get-movies) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L173
#### My DVD
- [ ] [Get DVD releases](https://trakt.docs.apiary.io/#reference/calendars/my-dvd/get-dvd-releases) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L214
#### All Shows
- [ ] [Get shows](https://trakt.docs.apiary.io/#reference/calendars/all-shows/get-shows) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L255
#### All New Shows
- [ ] [Get new shows](https://trakt.docs.apiary.io/#reference/calendars/all-new-shows/get-new-shows) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L296
#### All Season Premieres
- [ ] [Get season premieres](https://trakt.docs.apiary.io/#reference/calendars/all-season-premieres/get-season-premieres) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L337
#### All Movies
- [ ] [Get movies](https://trakt.docs.apiary.io/#reference/calendars/all-movies/get-movies) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L378
#### All DVD
- [ ] [Get DVD releases](https://trakt.docs.apiary.io/#reference/calendars/all-dvd/get-dvd-releases) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L419

**Comment by henrikfroehling** [comment]
### Checkin
- [ ] [Check into an item](https://trakt.docs.apiary.io/#reference/checkin/checkin/check-into-an-item) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCheckinsModule.cs#L49 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCheckinsModule.cs#L82
- [ ] [Delete any active checkins](https://trakt.docs.apiary.io/#reference/checkin/checkin/delete-any-active-checkins) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCheckinsModule.cs#L106

**Comment by henrikfroehling** [comment]
### Certifications
#### List
- [ ] [Get certifications](https://trakt.docs.apiary.io/#reference/certifications/list/get-certifications) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCertificationsModule.cs#L37 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCertificationsModule.cs#L56

**Comment by henrikfroehling** [comment]
### Comments
TODO

**Comment by henrikfroehling** [comment]
### Countries
#### List
- [ ] [Get countries](https://trakt.docs.apiary.io/#reference/countries/list/get-countries) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCountriesModule.cs#L37 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCountriesModule.cs#L56

**Comment by henrikfroehling** [comment]
### Genres
#### List
- [ ] [Get genres](https://trakt.docs.apiary.io/#reference/genres/list/get-genres) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktGenresModule.cs#L38 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktGenresModule.cs#L65

**Comment by henrikfroehling** [comment]
### Languages
#### List
- [ ] [Get languages](https://trakt.docs.apiary.io/#reference/languages/list/get-languages) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktLanguagesModule.cs#L37 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktLanguagesModule.cs#L56

**Comment by henrikfroehling** [comment]
### Lists
TODO

**Comment by henrikfroehling** [comment]
### Movies
TODO

**Comment by henrikfroehling** [comment]
### Networks
#### List
- [ ] [Get networks](https://trakt.docs.apiary.io/#reference/networks/list/get-networks) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktNetworksModule.cs#L37

**Comment by henrikfroehling** [comment]
### People
TODO

**Comment by henrikfroehling** [comment]
### Recommendations
#### Movies
- [ ] [Get movie recommendations](https://trakt.docs.apiary.io/#reference/recommendations/movies/get-movie-recommendations) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktRecommendationsModule.cs#L51

#### Hide Movie
- [ ] [Hide a movie recommendation](https://trakt.docs.apiary.io/#reference/recommendations/hide-movie/hide-a-movie-recommendation) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktRecommendationsModule.cs#L83

#### Shows
- [ ] [Get show recommendations](https://trakt.docs.apiary.io/#reference/recommendations/shows/get-show-recommendations) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktRecommendationsModule.cs#L120

#### Hide Show
- [ ] [Hide a show recommendation](https://trakt.docs.apiary.io/#reference/recommendations/hide-show/hide-a-show-recommendation) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktRecommendationsModule.cs#L152

**Comment by henrikfroehling** [comment]
### Scrobble
#### Start
- [ ] [Start watching in a media center](https://trakt.docs.apiary.io/#reference/scrobble/start/start-watching-in-a-media-center) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktScrobbleModule.cs#L50 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktScrobbleModule.cs#L134

#### Pause
- [ ] [Pause watching in a media center](https://trakt.docs.apiary.io/#reference/scrobble/pause/pause-watching-in-a-media-center) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktScrobbleModule.cs#L78 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktScrobbleModule.cs#L162

#### Stop
- [ ] [Stop or finish watching in a media center](https://trakt.docs.apiary.io/#reference/scrobble/stop/stop-or-finish-watching-in-a-media-center) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktScrobbleModule.cs#L106 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktScrobbleModule.cs#L190

**Comment by henrikfroehling** [comment]
### Search
TODO

**Comment by henrikfroehling** [comment]
### Shows
TODO

**Comment by henrikfroehling** [comment]
### Seasons
TODO

**Comment by henrikfroehling** [comment]
### Episodes
TODO

**Comment by henrikfroehling** [comment]
### Sync
TODO

**Comment by henrikfroehling** [comment]
### Users
TODO
