### ISSUE TITLE
Epic: Improve test coverage - Part 1

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#49]
TODO:
- [x] #1 Improve test coverage - Part 1
- [x] #50 Improve test coverage - Part 2
- [x] #51 Improve test coverage - Part 3
