### ISSUE TITLE
Version 1.4.0 - Checklist API Endpoints - Authentication Module

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#558]
#### Authorize
- [x] [Authorize Application](https://trakt.docs.apiary.io/#reference/authentication-oauth/authorize/authorize-application) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L154 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L164 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L175 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L194 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L208 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L219 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L230
  - [x] #463

#### Get Token
- [x] [Exchange code for `access_token`](https://trakt.docs.apiary.io/#reference/authentication-oauth/get-token/exchange-code-for-access_token) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L255 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L277 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L300 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L324 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L348
- [x] [Exchange `refresh_token` for `access_token`](https://trakt.docs.apiary.io/#reference/authentication-oauth/get-token/exchange-refresh_token-for-access_token) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L563 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L592 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L622 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L653 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L684

#### Revoke Token
- [x] [Revoke an `access_token`](https://trakt.docs.apiary.io/#reference/authentication-oauth/revoke-token/revoke-an-access_token) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L723 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L749 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L776 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L804

---

#### Device Code
- [x] [Generate new device codes](https://trakt.docs.apiary.io/#reference/authentication-devices/device-code/generate-new-device-codes) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L379 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L397

#### Get Token
- [x] [Poll for the `access_token`](https://trakt.docs.apiary.io/#reference/authentication-devices/get-token/poll-for-the-access_token) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L435 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L463 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L492 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktAuthenticationModule.cs#L521
