### ISSUE TITLE
Version 1.4.0 - Checklist API Endpoints - Calendar Module

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#559]
#### My Shows
- [x] [Get shows](https://trakt.docs.apiary.io/#reference/calendars/my-shows/get-shows) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L50
#### My New Shows
- [x] [Get new shows](https://trakt.docs.apiary.io/#reference/calendars/my-new-shows/get-new-shows) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L91
#### My Season Premieres
- [x] [Get season premieres](https://trakt.docs.apiary.io/#reference/calendars/my-season-premieres/get-season-premieres) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L132
#### My Movies
- [x] [Get movies](https://trakt.docs.apiary.io/#reference/calendars/my-movies/get-movies) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L173
#### My DVD
- [x] [Get DVD releases](https://trakt.docs.apiary.io/#reference/calendars/my-dvd/get-dvd-releases) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L214
#### All Shows
- [x] [Get shows](https://trakt.docs.apiary.io/#reference/calendars/all-shows/get-shows) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L255
#### All New Shows
- [x] [Get new shows](https://trakt.docs.apiary.io/#reference/calendars/all-new-shows/get-new-shows) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L296
#### All Season Premieres
- [x] [Get season premieres](https://trakt.docs.apiary.io/#reference/calendars/all-season-premieres/get-season-premieres) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L337
#### All Movies
- [x] [Get movies](https://trakt.docs.apiary.io/#reference/calendars/all-movies/get-movies) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L378
#### All DVD
- [x] [Get DVD releases](https://trakt.docs.apiary.io/#reference/calendars/all-dvd/get-dvd-releases) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCalendarModule.cs#L419
