### ISSUE TITLE
Version 1.4.0 - Checklist API Endpoints - Comments Module

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#562]
#### Comments
- [x] [Post a comment](https://trakt.docs.apiary.io/#reference/comments/comments/post-a-comment) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCommentsModule.cs#L363 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCommentsModule.cs#L396 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCommentsModule.cs#L429 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCommentsModule.cs#L462 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCommentsModule.cs#L495

#### Comment
- [x] [Get a comment or reply](https://trakt.docs.apiary.io/#reference/comments/comment/get-a-comment-or-reply) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCommentsModule.cs#L56 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCommentsModule.cs#L182 
  - [x] #464
  - [x] #487
- [x] [Update a comment or reply](https://trakt.docs.apiary.io/#reference/comments/comment/update-a-comment-or-reply) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCommentsModule.cs#L525
- [x] [Delete a comment or reply](https://trakt.docs.apiary.io/#reference/comments/comment/delete-a-comment-or-reply) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCommentsModule.cs#L591

#### Replies
- [x] [Get replies for a comment](https://trakt.docs.apiary.io/#reference/comments/replies/get-replies-for-a-comment) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCommentsModule.cs#L674
  - [x] #494
- [x] [Post a reply for a comment](https://trakt.docs.apiary.io/#reference/comments/replies/post-a-reply-for-a-comment) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCommentsModule.cs#L560

#### Item
- [x] [Get the attached media item](https://trakt.docs.apiary.io/#reference/comments/item/get-the-attached-media-item) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCommentsModule.cs#L78

#### Likes
- [x] [Get all users who liked a comment](https://trakt.docs.apiary.io/#reference/comments/likes/get-all-users-who-liked-a-comment) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCommentsModule.cs#L117

#### Like
- [x] [Like a comment](https://trakt.docs.apiary.io/#reference/comments/like/like-a-comment) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCommentsModule.cs#L616
- [x] [Remove like on a comment](https://trakt.docs.apiary.io/#reference/comments/like/remove-like-on-a-comment) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCommentsModule.cs#L641

#### Trending
- [x] [Get trending comments](https://trakt.docs.apiary.io/#reference/comments/trending/get-trending-comments) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCommentsModule.cs#L322

#### Recent
- [x] [Get recently created comments](https://trakt.docs.apiary.io/#reference/comments/recent/get-recently-created-comments) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCommentsModule.cs#L275

#### Updates
- [x] [Get recently updated comments](https://trakt.docs.apiary.io/#reference/comments/updates/get-recently-updated-comments) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktCommentsModule.cs#L228
