### ISSUE TITLE
Version 1.4.0 - Checklist API Endpoints - Lists Module

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#566]
#### Trending
- [x] [Get trending lists](https://trakt.docs.apiary.io/#reference/lists/trending/get-trending-lists) https://github.com/henrikfroehling/Trakt.NET/blob/7221bada7cdb7e0b5fc50ed666526ccb6f4d3b67/Source/Lib/Trakt.NET/Modules/TraktListsModule.cs#L89
  - [x] #466
  - [x] #488

#### Popular
- [x] [Get popular lists](https://trakt.docs.apiary.io/#reference/lists/popular/get-popular-lists) https://github.com/henrikfroehling/Trakt.NET/blob/7221bada7cdb7e0b5fc50ed666526ccb6f4d3b67/Source/Lib/Trakt.NET/Modules/TraktListsModule.cs#L51
  - [x] #466
  - [x] #489

#### List
- [x] [Get list](https://trakt.docs.apiary.io/#reference/lists/list/get-list) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktListsModule.cs#L106
  - [x] #461
  - [x] #462
  - [x] #490
  - [x] #526

#### List Likes
- [x] [Get all users who liked a list](https://trakt.docs.apiary.io/#reference/lists/list-likes/get-all-users-who-liked-a-list) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktListsModule.cs#L168
  - [x] #467

#### List Like
- [x] [Like a list](https://trakt.docs.apiary.io/#reference/lists/list-like/like-a-list) https://github.com/henrikfroehling/Trakt.NET/blob/22fce5998eea2cb1048e1c5c43abf975734a49f5/Source/Lib/Trakt.NET/Modules/TraktListsModule.cs#L219
https://github.com/henrikfroehling/Trakt.NET/blob/22fce5998eea2cb1048e1c5c43abf975734a49f5/Source/Lib/Trakt.NET/Modules/TraktListsModule.cs#L245
https://github.com/henrikfroehling/Trakt.NET/blob/22fce5998eea2cb1048e1c5c43abf975734a49f5/Source/Lib/Trakt.NET/Modules/TraktListsModule.cs#L274
  - [x] #585

- [x] [Remove like on a list](https://trakt.docs.apiary.io/#reference/lists/list-like/remove-like-on-a-list) https://github.com/henrikfroehling/Trakt.NET/blob/22fce5998eea2cb1048e1c5c43abf975734a49f5/Source/Lib/Trakt.NET/Modules/TraktListsModule.cs#L302
https://github.com/henrikfroehling/Trakt.NET/blob/22fce5998eea2cb1048e1c5c43abf975734a49f5/Source/Lib/Trakt.NET/Modules/TraktListsModule.cs#L328
https://github.com/henrikfroehling/Trakt.NET/blob/22fce5998eea2cb1048e1c5c43abf975734a49f5/Source/Lib/Trakt.NET/Modules/TraktListsModule.cs#L357
  - [x] #586

#### List Items
- [x] [Get items on a list](https://trakt.docs.apiary.io/#reference/lists/list-items/get-items-on-a-list) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktListsModule.cs#L137

#### List Comments
- [x] [Get all list comments](https://trakt.docs.apiary.io/#reference/lists/list-comments/get-all-list-comments) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktListsModule.cs#L203
  - [x] #491
