### ISSUE TITLE
Version 1.4.0 - Checklist API Endpoints - Movies Module

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#567]
#### Trending
- [x] [Get trending movies](https://trakt.docs.apiary.io/#reference/movies/trending/get-trending-movies) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L505

#### Popular
- [x] [Get popular movies](https://trakt.docs.apiary.io/#reference/movies/popular/get-popular-movies) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L550

#### Favorited
- [x] [Get the most favorited movies](https://trakt.docs.apiary.io/#reference/movies/favorited/get-the-most-favorited-movies) https://github.com/henrikfroehling/Trakt.NET/blob/fa8f8d8b29c09acf99e2e990fe190ec54aa6f673/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L785
  - [x] #522

#### Played
- [x] [Get the most played movies](https://trakt.docs.apiary.io/#reference/movies/played/get-the-most-played-movies) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L596

#### Watched
- [x] [Get the most watched movies](https://trakt.docs.apiary.io/#reference/movies/watched/get-the-most-watched-movies) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L644

#### Collected
- [x] [Get the most collected movies](https://trakt.docs.apiary.io/#reference/movies/collected/get-the-most-collected-movies) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L692

#### Anticipated
- [x] [Get the most anticipated movies](https://trakt.docs.apiary.io/#reference/movies/anticipated/get-the-most-anticipated-movies) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L739

#### Box Office
- [x] [Get the weekend box office](https://trakt.docs.apiary.io/#reference/movies/box-office/get-the-weekend-box-office) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L820

#### Updated
- [x] [Get recently updated movies](https://trakt.docs.apiary.io/#reference/movies/updates/get-recently-updated-movies) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L857

#### Updated IDs
- [x] [Get recently updated movie Trakt IDs](https://trakt.docs.apiary.io/#reference/movies/updated-ids/get-recently-updated-movie-trakt-ids) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L894

#### Summary
- [x] [Get a movie](https://trakt.docs.apiary.io/#reference/movies/summary/get-a-movie) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L53 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L108

#### Aliases
- [x] [Get all movie aliases](https://trakt.docs.apiary.io/#reference/movies/aliases/get-all-movie-aliases) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L143

#### Releases
- [x] [Get all movie releases](https://trakt.docs.apiary.io/#reference/movies/releases/get-all-movie-releases) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L171

#### Translations
- [x] [Get all movie translations](https://trakt.docs.apiary.io/#reference/movies/translations/get-all-movie-translations) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L200
  - [x] #468

#### Comments
- [x] [Get all movie comments](https://trakt.docs.apiary.io/#reference/movies/comments/get-all-movie-comments) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L236
  - [x] #469
  - [x] #495

#### Lists
- [x] [Get lists containing this movie](https://trakt.docs.apiary.io/#reference/movies/lists/get-lists-containing-this-movie) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L276
  - [x] #492

#### People
- [x] [Get all people for a movie](https://trakt.docs.apiary.io/#reference/movies/people/get-all-people-for-a-movie) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L312

#### Ratings
- [x] [Get movie ratings](https://trakt.docs.apiary.io/#reference/movies/ratings/get-movie-ratings) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L340

#### Related
- [x] [Get related movies](https://trakt.docs.apiary.io/#reference/movies/related/get-related-movies) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L377

#### Stats
- [x] [Get movie stats](https://trakt.docs.apiary.io/#reference/movies/stats/get-movie-stats) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L407

#### Studios
- [x] [Get movie studios](https://trakt.docs.apiary.io/#reference/movies/studios/get-movie-studios) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L465

#### Watching
- [x] [Get users watching right now](https://trakt.docs.apiary.io/#reference/movies/watching/get-users-watching-right-now) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L437
