### ISSUE TITLE
Version 1.4.0 - Checklist API Endpoints - People Module

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#569]
#### Updates
- [x] [Get recently updated people](https://trakt.docs.apiary.io/#reference/people/updates/get-recently-updated-people) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktPeopleModule.cs#L291

#### Updated IDs
- [x] [Get recently updated people Trakt IDs](https://trakt.docs.apiary.io/#reference/people/updated-ids/get-recently-updated-people-trakt-ids) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktPeopleModule.cs#L253

#### Summary
- [x] [Get a single person](https://trakt.docs.apiary.io/#reference/people/summary/get-a-single-person) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktPeopleModule.cs#L52 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktPeopleModule.cs#L107
  - [x] #458
  - [x] #459

#### Movies
- [x] [Get movie credits](https://trakt.docs.apiary.io/#reference/people/movies/get-movie-credits) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktPeopleModule.cs#L146

#### Shows
- [x] [Get show credits](https://trakt.docs.apiary.io/#reference/people/shows/get-show-credits) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktPeopleModule.cs#L178

#### Lists
- [x] [Get lists containing this person](https://trakt.docs.apiary.io/#reference/people/lists/get-lists-containing-this-person) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktPeopleModule.cs#L215
  - [x] #493
