### ISSUE TITLE
Version 1.4.0 - Checklist API Endpoints - Recommendations Module

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#570]
#### Movies
- [x] [Get movie recommendations](https://trakt.docs.apiary.io/#reference/recommendations/movies/get-movie-recommendations) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktRecommendationsModule.cs#L51
  - [x] #470
  - [x] #557

#### Hide Movie
- [x] [Hide a movie recommendation](https://trakt.docs.apiary.io/#reference/recommendations/hide-movie/hide-a-movie-recommendation) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktRecommendationsModule.cs#L83

#### Shows
- [x] [Get show recommendations](https://trakt.docs.apiary.io/#reference/recommendations/shows/get-show-recommendations) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktRecommendationsModule.cs#L120
  - [x] #470
  - [x] #557

#### Hide Show
- [x] [Hide a show recommendation](https://trakt.docs.apiary.io/#reference/recommendations/hide-show/hide-a-show-recommendation) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktRecommendationsModule.cs#L152
