### ISSUE TITLE
Version 1.4.0 - Checklist API Endpoints - Scrobble Module

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#571]
#### Start
- [x] [Start watching in a media center](https://trakt.docs.apiary.io/#reference/scrobble/start/start-watching-in-a-media-center) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktScrobbleModule.cs#L50 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktScrobbleModule.cs#L134

#### Pause
- [x] [Pause watching in a media center](https://trakt.docs.apiary.io/#reference/scrobble/pause/pause-watching-in-a-media-center) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktScrobbleModule.cs#L78 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktScrobbleModule.cs#L162

#### Stop
- [x] [Stop or finish watching in a media center](https://trakt.docs.apiary.io/#reference/scrobble/stop/stop-or-finish-watching-in-a-media-center) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktScrobbleModule.cs#L106 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktScrobbleModule.cs#L190
