### ISSUE TITLE
Version 1.4.0 - Checklist API Endpoints - Shows Module

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#573]
#### Trending
- [x] [Get trending shows](https://trakt.docs.apiary.io/#reference/shows/trending/get-trending-shows) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L703

#### Popular
- [x] [Get popular shows](https://trakt.docs.apiary.io/#reference/shows/popular/get-popular-shows) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L748

#### Favorited
- [x] [Get the most favorited shows](https://trakt.docs.apiary.io/#reference/shows/favorited/get-the-most-favorited-shows) https://github.com/henrikfroehling/Trakt.NET/blob/fa8f8d8b29c09acf99e2e990fe190ec54aa6f673/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L983
  - [x] #523

#### Played
- [x] [Get the most played shows](https://trakt.docs.apiary.io/#reference/shows/played/get-the-most-played-shows) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L794

#### Watched
- [x] [Get the most watched shows](https://trakt.docs.apiary.io/#reference/shows/watched/get-the-most-watched-shows) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L842

#### Collected
- [x] [Get the most collected shows](https://trakt.docs.apiary.io/#reference/shows/watched/get-the-most-collected-shows) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L890

#### Anticipated
- [x] [Get the most anticipated shows](https://trakt.docs.apiary.io/#reference/shows/anticipated/get-the-most-anticipated-shows) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L937

#### Updates
- [x] [Get recently updated shows](https://trakt.docs.apiary.io/#reference/shows/updates/get-recently-updated-shows) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L1026

#### Updated IDs
- [x] [Get recently updated show Trakt IDs](https://trakt.docs.apiary.io/#reference/shows/updates/get-recently-updated-show-trakt-ids) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L1063

#### Summary
- [x] [Get a single show](https://trakt.docs.apiary.io/#reference/shows/summary/get-a-single-show) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L56 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L111

#### Aliases
- [x] [Get all show aliases](https://trakt.docs.apiary.io/#reference/shows/aliases/get-all-show-aliases) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L146

#### Certifications
- [x] [Get all show certifications](https://trakt.docs.apiary.io/#reference/shows/certifications/get-all-show-certifications) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L663

#### Translations
- [x] [Get all show translations](https://trakt.docs.apiary.io/#reference/shows/translations/get-all-show-translations) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L173
  - [x] #468

#### Comments
- [x] [Get all show comments](https://trakt.docs.apiary.io/#reference/shows/comments/get-all-show-comments) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L209
  - [x] #474
  - [x] #496

#### Lists
- [x] [Get lists containing this show](https://trakt.docs.apiary.io/#reference/shows/lists/get-lists-containing-this-show) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L249
  - [x] #497

#### Collection Progress
- [x] [Get show collection progress](https://trakt.docs.apiary.io/#reference/shows/collection-progress/get-show-collection-progress) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L442
  - [x] #475

#### Watched Progress
- [x] [Get show watched progress](https://trakt.docs.apiary.io/#reference/shows/watched-progress/get-show-watched-progress) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L480
  - [x] #475

#### Reset Watched Progress
- [x] [Reset show progress](https://trakt.docs.apiary.io/#reference/shows/reset-watched-progress/reset-show-progress) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L516
- [x] [Undo reset show progress](https://trakt.docs.apiary.io/#reference/shows/reset-watched-progress/undo-reset-show-progress) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L547

#### People
- [x] [Get all people for a show](https://trakt.docs.apiary.io/#reference/shows/people/get-all-people-for-a-show) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L285

#### Ratings
- [x] [Get show ratings](https://trakt.docs.apiary.io/#reference/shows/ratings/get-show-ratings) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L313

#### Related
- [x] [Get related shows](https://trakt.docs.apiary.io/#reference/shows/related/get-related-shows) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L350

#### Stats
- [x] [Get show stats](https://trakt.docs.apiary.io/#reference/shows/stats/get-show-stats) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L380

#### Studios
- [x] [Get show studios](https://trakt.docs.apiary.io/#reference/shows/studios/get-show-studios) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L637

#### Watching
- [x] [Get users watching right now](https://trakt.docs.apiary.io/#reference/shows/watching/get-users-watching-right-now) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L410

#### Next Episode
- [x] [Get next episode](https://trakt.docs.apiary.io/#reference/shows/next-episode/get-next-episode) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L577

#### Last Episode
- [x] [Get last episode](https://trakt.docs.apiary.io/#reference/shows/last-episode/get-last-episode) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L609
