### ISSUE TITLE
Version 1.4.0 - Checklist API Endpoints - Seasons Module

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#574]
#### Summary
- [x] [Get all seasons for a show](https://trakt.docs.apiary.io/#reference/seasons/summary/get-all-seasons-for-a-show) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSeasonsModule.cs#L58

#### Season
- [x] [Get single season for a show](https://trakt.docs.apiary.io/#reference/seasons/season/get-single-season-for-a-show) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSeasonsModule.cs#L99 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSeasonsModule.cs#L158

#### Translations
- [x] [Get all season translations](https://trakt.docs.apiary.io/#reference/seasons/translations/get-all-season-translations) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSeasonsModule.cs#L373
  - [x] #468

#### Comments
- [x] [Get all season comments](https://trakt.docs.apiary.io/#reference/seasons/comments/get-all-season-comments) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSeasonsModule.cs#L204
  - [x] #474
  - [x] #498

#### Lists
- [x] [Get lists containing this season](https://trakt.docs.apiary.io/#reference/seasons/lists/get-lists-containing-this-season) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSeasonsModule.cs#L246
  - [x] #499

#### People
- [x] [Get all people for a season](https://trakt.docs.apiary.io/#reference/seasons/people/get-all-people-for-a-season) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSeasonsModule.cs#L284

#### Ratings
- [x] [Get season ratings](https://trakt.docs.apiary.io/#reference/seasons/ratings/get-season-ratings) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSeasonsModule.cs#L314

#### Stats
- [x] [Get season stats](https://trakt.docs.apiary.io/#reference/seasons/stats/get-season-stats) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSeasonsModule.cs#L343

#### Watching
- [x] [Get users watching right now](https://trakt.docs.apiary.io/#reference/seasons/watching/get-users-watching-right-now) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSeasonsModule.cs#L407
