### ISSUE TITLE
Version 1.4.0 - Checklist API Endpoints - Episodes Module

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#575]
#### Summary
- [x] [Get a single episode for a show](https://trakt.docs.apiary.io/#reference/episodes/summary/get-a-single-episode-for-a-show) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktEpisodesModule.cs#L56 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktEpisodesModule.cs#L113

#### Translations
- [x] [Get all episode translations](https://trakt.docs.apiary.io/#reference/episodes/translations/get-all-episode-translations) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktEpisodesModule.cs#L339
  - [x] #468

#### Comments
- [x] [Get all episode comments](https://trakt.docs.apiary.io/#reference/episodes/comments/get-all-episode-comments) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktEpisodesModule.cs#L159
  - [x] #469
  - [x] #500

#### Lists
- [x] [Get lists containing this episode](https://trakt.docs.apiary.io/#reference/episodes/lists/get-lists-containing-this-episode) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktEpisodesModule.cs#L203
  - [x] #501

#### People
- [x] [Get all people for an episode](https://trakt.docs.apiary.io/#reference/episodes/people/get-all-people-for-an-episode) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktEpisodesModule.cs#L243

#### Ratings
- [x] [Get episode ratings](https://trakt.docs.apiary.io/#reference/episodes/ratings/get-episode-ratings) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktEpisodesModule.cs#L276

#### Stats
- [x] [Get episode stats](https://trakt.docs.apiary.io/#reference/episodes/stats/get-episode-stats) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktEpisodesModule.cs#L307

#### Watching
- [x] [Get users watching right now](https://trakt.docs.apiary.io/#reference/episodes/watching/get-users-watching-right-now) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktEpisodesModule.cs#L376
