### ISSUE TITLE
Version 1.4.0 - Checklist API Endpoints - Sync Module

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#576]
#### Last Activity
- [x] [Get last activity](https://trakt.docs.apiary.io/#reference/sync/last-activities/get-last-activity) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L60
  - [x] #478

#### Playback Progress
- [x] [Get playback progress](https://trakt.docs.apiary.io/#reference/sync/playback/get-playback-progress) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L154

#### Remove Playback
- [x] [Remove a playback item](https://trakt.docs.apiary.io/#reference/sync/remove-playback/remove-a-playback-item) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L186

#### Get Collection
- [x] [Get collection](https://trakt.docs.apiary.io/#reference/sync/get-collection/get-collection) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L217 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L246

#### Add to Collection
- [x] [Add items to collection](https://trakt.docs.apiary.io/#reference/sync/add-to-collection/add-items-to-collection) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L279

#### Remove from Collection
- [x] [Remove items from collection](https://trakt.docs.apiary.io/#reference/sync/remove-from-collection/remove-items-from-collection) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L312

#### Get Watched
- [x] [Get watched](https://trakt.docs.apiary.io/#reference/sync/get-watched/get-watched) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L341 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L370

#### Get History
- [x] [Get history](https://trakt.docs.apiary.io/#reference/sync/get-history/get-watched-history) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L410

#### Add to History
- [x] [Add items to watched history](https://trakt.docs.apiary.io/#reference/sync/add-to-history/add-items-to-watched-history) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L451

#### Remove from History
- [x] [Remove items from watched history](https://trakt.docs.apiary.io/#reference/sync/remove-from-history/remove-items-from-history) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L484

#### Get Ratings
- [x] [Get ratings](https://trakt.docs.apiary.io/#reference/sync/get-ratings/get-ratings) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L520

#### Add Ratings
- [x] [Add new ratings](https://trakt.docs.apiary.io/#reference/sync/add-ratings/add-new-ratings) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L559

#### Remove Ratings
- [x] [Remove ratings](https://trakt.docs.apiary.io/#reference/sync/remove-ratings/remove-ratings) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L592

#### Get Watchlist
- [x] [Get watchlist](https://trakt.docs.apiary.io/#reference/sync/get-watchlist/get-watchlist) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L696

#### Add to Watchlist
- [x] [Add items to watchlist](https://trakt.docs.apiary.io/#reference/sync/add-to-watchlist/add-items-to-watchlist) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L766

#### Remove from Watchlist
- [x] [Remove items from watchlist](https://trakt.docs.apiary.io/#reference/sync/remove-from-watchlist/remove-items-from-watchlist) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L799

#### Reorder Watchlist
- [x] [Reorder watchlist items](https://trakt.docs.apiary.io/#reference/sync/reorder-watchlist/reorder-watchlist-items) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L730
  - [x] #479

#### Update Watchlist Item
- [x] [Update a watchlist item](https://trakt.docs.apiary.io/#reference/sync/update-watchlist-item/update-a-watchlist-item) https://github.com/henrikfroehling/Trakt.NET/blob/327343d620d7d7314293452c4b3d357bbbb7e0aa/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L792
  - [x] #485

#### Get Favorites
- [x] [Get favorites](https://trakt.docs.apiary.io/#reference/sync/get-favorites/get-favorites) https://github.com/henrikfroehling/Trakt.NET/blob/1f8d1582db907afc70e411be092f3efdbf2b247f/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L90
  - [x] #480
  - [x] #556

#### Add to Favorites
- [x] [Add items to favorites](https://trakt.docs.apiary.io/#reference/sync/add-to-favorites/add-items-to-favorites) https://github.com/henrikfroehling/Trakt.NET/blob/1f8d1582db907afc70e411be092f3efdbf2b247f/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L656
  - [x] #556

#### Remove from Favorites
- [x] [Remove items from favorites](https://trakt.docs.apiary.io/#reference/sync/remove-from-favorites/remove-items-from-favorites) https://github.com/henrikfroehling/Trakt.NET/blob/1f8d1582db907afc70e411be092f3efdbf2b247f/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L689
  - [x] #556

#### Reorder Favorites
- [x] [Reorder favorites](https://trakt.docs.apiary.io/#reference/sync/reorder-favorites/reorder-favorited-items) https://github.com/henrikfroehling/Trakt.NET/blob/1f8d1582db907afc70e411be092f3efdbf2b247f/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L122
  - [x] #556

#### Update Favorite Item
- [x] [Update a favorite item](https://trakt.docs.apiary.io/#reference/sync/update-favorite-item/update-a-favorite-item) https://github.com/henrikfroehling/Trakt.NET/blob/327343d620d7d7314293452c4b3d357bbbb7e0aa/Source/Lib/Trakt.NET/Modules/TraktSyncModule.cs#L153
  - [x] #486
