### ISSUE TITLE
Version 1.4.0 - Checklist API Endpoints - Users Module

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#577]
#### Settings
- [x] [Retrieve settings](https://trakt.docs.apiary.io/#reference/users/settings/retrieve-settings) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L60

#### Following Requests
- [x] [Get pending following requests](https://trakt.docs.apiary.io/#reference/users/following-requests/get-pending-following-requests) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L112

#### Follower Requests
- [x] [Get follow requests](https://trakt.docs.apiary.io/#reference/users/follower-requests/get-follow-requests) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L83

#### Approve or Deny Follower Requests
- [x] [Approve follow request](https://trakt.docs.apiary.io/#reference/users/approve-or-deny-follower-requests/approve-follow-request) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L1185
- [x] [Deny follow request](https://trakt.docs.apiary.io/#reference/users/approve-or-deny-follower-requests/deny-follow-request) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L1210

#### Saved Filters
- [x] [Get saved filters](https://trakt.docs.apiary.io/#reference/users/saved-filters/get-saved-filters) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L191
  - [x] #481

#### Hidden Items
- [x] [Get hidden items](https://trakt.docs.apiary.io/#reference/users/hidden-items/get-hidden-items) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L151
  - [x] #482
  - [x] #483

#### Add Hidden Items
- [x] [Add hidden items](https://trakt.docs.apiary.io/#reference/users/add-hidden-items/add-hidden-items) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L227

#### Remove Hidden Items
- [x] [Remove hidden items](https://trakt.docs.apiary.io/#reference/users/remove-hidden-items/remove-hidden-items) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L263

#### Profile
- [x] [Get user profile](https://trakt.docs.apiary.io/#reference/users/profile/get-user-profile) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L331

#### Likes
- [x] [Get likes](https://trakt.docs.apiary.io/#reference/users/likes/get-likes) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L298

#### Collection
- [x] [Get collection](https://trakt.docs.apiary.io/#reference/users/collection/get-collection) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L363 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L396

#### Comments
- [x] [Get comments](https://trakt.docs.apiary.io/#reference/users/comments/get-comments) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L439

#### Lists
- [x] [Get a user's personal lists](https://trakt.docs.apiary.io/#reference/users/lists/get-a-user's-personal-lists) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L476
- [x] [Create personal list](https://trakt.docs.apiary.io/#reference/users/lists/create-personal-list) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L636
  - [x] #461

#### Reorder Lists
- [x] [Reorder a user's list](https://trakt.docs.apiary.io/#reference/users/reorder-lists/reorder-a-user's-lists) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L699

#### Collaborations
- [x] [Get all lists a user can collaborate on](https://trakt.docs.apiary.io/#reference/users/collaborations/get-all-lists-a-user-can-collaborate-on) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L1008

#### List
- [x] [Get personal list](https://trakt.docs.apiary.io/#reference/users/list/get-personal-list) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L504 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L559
- [x] [Update personal list](https://trakt.docs.apiary.io/#reference/users/list/update-personal-list) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L667
  - [x] #461
- [x] [Delete a user's personal list](https://trakt.docs.apiary.io/#reference/users/list/delete-a-user's-personal-list) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L766

#### List Likes
- [x] [Get all users who liked a list](https://trakt.docs.apiary.io/#reference/users/list-likes/get-all-users-who-liked-a-list) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L922

#### List Like
- [x] [Like a list](https://trakt.docs.apiary.io/#reference/users/list-like/like-a-list) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L952
- [x] [Remove like on a list](https://trakt.docs.apiary.io/#reference/users/list-like/remove-like-on-a-list) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L980

#### List Items
- [x] [Get all items on a personal list](https://trakt.docs.apiary.io/#reference/users/list-items/get-items-on-a-personal-list) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L601

#### Add List Items
- [x] [Add items to personal list](https://trakt.docs.apiary.io/#reference/users/add-list-items/add-items-to-personal-list) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L802

#### Remove List Items
- [x] [Remove items from personal list](https://trakt.docs.apiary.io/#reference/users/remove-list-items/remove-items-from-personal-list) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L840

#### Reorder List Items
- [x] [Reorder items on a list](https://trakt.docs.apiary.io/#reference/users/reorder-list-items/reorder-items-on-a-list) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L733

#### Update List Item
- [x] [Update a list item](https://trakt.docs.apiary.io/#reference/users/update-list-item/update-a-list-item) https://github.com/henrikfroehling/Trakt.NET/blob/9bb3381e5bddacc64aa8a8c1af583bdbc4705ce3/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L769
  - [x] #484

#### List Comments
- [x] [Get all list comments](https://trakt.docs.apiary.io/#reference/users/list-comments/get-all-list-comments) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L879

#### Follow
- [x] [Follow this user](https://trakt.docs.apiary.io/#reference/users/follow/follow-this-user) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L1133
- [x] [Unfollow this user](https://trakt.docs.apiary.io/#reference/users/follow/unfollow-this-user) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L1159

#### Followers
- [x] [Get followers](https://trakt.docs.apiary.io/#reference/users/followers/get-followers) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L1038

#### Following
- [x] [Get following](https://trakt.docs.apiary.io/#reference/users/following/get-following) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L1070

#### Friends
- [x] [Get friends](https://trakt.docs.apiary.io/#reference/users/friends/get-friends) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L1102

#### History
- [x] [Get watched history](https://trakt.docs.apiary.io/#reference/users/history/get-watched-history) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L1251

#### Ratings
- [x] [Get ratings](https://trakt.docs.apiary.io/#reference/users/ratings/get-ratings) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L1341

#### Watchlist
- [x] [Get watchlist](https://trakt.docs.apiary.io/#reference/users/watchlist/get-watchlist) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L1387

#### Favorites
- [x] #555
- [x] [Get favorites](https://trakt.docs.apiary.io/#reference/users/favorites/get-favorites) https://github.com/henrikfroehling/Trakt.NET/blob/e36b1b9271988ddf99422ba49925cb8af374eca8/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L1334
  - [x] #480

#### Watching
- [x] [Get watching](https://trakt.docs.apiary.io/#reference/users/watching/get-watching) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L1425

#### Watched
- [x] [Get watched](https://trakt.docs.apiary.io/#reference/users/watched/get-watched) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L1457 https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L1489

#### Stats
- [x] [Get stats](https://trakt.docs.apiary.io/#reference/users/stats/get-stats) https://github.com/henrikfroehling/Trakt.NET/blob/dfb19cdff15f7121e9209d354b969edb35320624/Source/Lib/Trakt.NET/Modules/TraktUsersModule.cs#L1517
