### ISSUE TITLE
Version 1.1.0 ToDo

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#86]
**Version 1.1.0**
- [x] #5 Improve post request builder
- [x] #55 Remove Facebook sharing
- [x] #58 Improve / replace UriTemplate implementation
- [x] #59 Add support for "users/{username}/lists/reorder" POST request
- [x] #66 Add support for "users/{username}/lists/{list_id}/items/reorder" POST request
- [x] #67 Add support for "date_format" property in ITraktAccountSettings
- [x] #68 Add support for "last_updated_at" property in "ITraktWatchedShow"
- [x] #69 Add support for "last_updated_at" property in "ITraktCollectionShow"
- [x] #74 Improve implementation of filters
- [x] #76 Add support for "countries/{type}" GET request 
- [x] #77 Add support for "languages/{type}" GET request
- [x] #78 Add support for "updated_at" property in "ITraktCollectionMovie"
- [x] #79 Add support for "last_updated_at" property in "ITraktWatchedMovie"
- [x] #81 Add support for absolute episode numbers in "/checkin" POST request
- [x] #82 Add support for absolute episode numbers in "/scrobble" POST request
- [x] #83 Add support for "last_activity" flag in "shows/{id}/progress/collection" GET request
- [x] #84 Add support for "last_activity" flag in "shows/{id}/progress/watched" GET request
- [x] #85 Add support for "include_replies=only" flag in "users/{username}/comments" GET request
- [x] #87 Convert test project to xUnit .NET Core
- [x] #95 Merge GH-94: Redundant checks for ITraktMovie properties in TraktScrobbleModule
- [x] #98 Missing properties in ITraktMetadata
- [x] #99 Split up test project in multiple test projects (develop)
- [x] #104 Add support for "ignore_collected" flag in "recommendations/movies" GET request
- [x] #105 Add support for "ignore_collected" flag in "recommendations/shows" GET request
- [x] #116 Split up TraktNET.Objects.Tests in multiple test projects (develop)
- [x] #126 Add support for "reset_at" flag in "sync/watched/shows" GET request
- [x] #127 Add support for "reset_at" flag in "users/{username}/watched/shows" GET request
- [x] #128 Add support for pagination for "sync/ratings" GET request
- [x] #129 Add support for pagination for "users/{username}/ratings" GET request
- [x] #135 Remove prefix "X" from property names in ITraktResponseHeaders
- [x] #136 Add support for new response headers "X-Applied-Sort-By" and "X-Applied-Sort-How"
- [x] #137 Add support for sorting in "sync/watchlist" GET request
- [x] #138 Add support for sorting in "users/{username}/watchlist/" GET request
- [x] #142 Remove deprecated properties due to new people methods
- [x] #143 Improve JSON reader implementation
- [x] #162 Add support for "uuid" property in ITraktUserIds
- [x] #166 Add support for "users/{id}/recommendations/{type}/{sort}" GET request
- [x] #175 Add support for "status" property in ITraktMovie
- [x] #184 Adding GuestStars as ExtendedInfo when calling GetEpisodePeopleAsync does not return the guest starts
- [x] #185 Return same instance type for people requests in Episodes, Shows and Seasons module
