### ISSUE TITLE
Rename Visual Studio project

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#9]
- [x] #10 Replace all occurrences of "TraktApiSharp" with "Trakt.NET" in Visual Studio project files (.csproj) / Rename project files
- [x] #11 Replace all occurrences of "TraktApiSharp" with "Trakt.NET" in Visual Studio solution files (.sln) / Rename solution files
- [x] #12 Replace all occurrences of "TraktApiSharp" with "Trakt.NET" in appveyor.yml
- [x] #13 Create new NuGet package with the name "Trakt.NET"
