### ISSUE TITLE
Epic: Improve test coverage - Part 2

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/Trakt.NET#97]
- [x] #52 Improve test coverage - Part 4
- [x] #53 Improve test coverage - Part 5
- [x] #54 Improve test coverage - Part 6
